### ISSUE TITLE
Advanced Macros?

### ISSUE THREAD

**Issue by MrVauxs** [reonZ/mc-ro#1]
Is this a continuation of Advanced Macros? A different implementation?
Would be nice to have that cleared up in the README. As far as I see, this is a carbon copy in the advertised functionality, so that confused me a fair bit.

**Comment by p4535992** [comment]
I too see the features of this module very similar to those provided by "Advanced Macro," perhaps it would be more correct to add the features of this module as an addition to the "advanced macro" module ? perhaps with a PR to unify the best of these two modules would be something to consider.

**Comment by reonZ** [comment]
> Is this a continuation of Advanced Macros? A different implementation? Would be nice to have that cleared up in the README. As far as I see, this is a carbon copy in the advertised functionality.

This is my own module and not a continuation of anything, having more than one module having similar functionalities is not a bad thing, if you like one more than the other then you are welcome to use that one.

I create modules for myself first when i have a need and time to do so, then i publish them when they are polished enough. I don't see why i should "clear" anything up in the README,

**Comment by reonZ** [comment]
I mean, if you take 30 sec and look at this README and `Advanced Macros`, you can clearly see there are very little similitude in the way both are implemented. I don't understand how you could have come up with the idea of this one being a fork/continuation of the other.

But they are focusing on the same feature that is true.

**Comment by MrVauxs** [comment]
> I mean, if you take 30 sec and look at this README and `Advanced Macros`, you can clearly see there are very little similitude in the way both are implemented. I don't understand how you could have come up with the idea of this one being a fork/continuation of the other.
> 
> But they are focusing on the same feature that is true.

Was simply asking to clear something up.
I'm assuming the two are incompatible together though. That's at least worth mentioning to the average user.

**Comment by reonZ** [comment]
> Was simply asking to clear something up. I'm assuming the two are incompatible together though. That's at least worth mentioning to the average user.

That is not really what you did, you told me that i should justify myself on my README.

There are a lot of modules out there that do the same thing, i don't see the problem, and you don't use 2 modules that do the same, i shouldn't have to go around and look for all the modules that have similar features to mines and warn user about them.

I find my README pretty clear about what this module does, there is no real ambiguity.
