### ISSUE TITLE
Macro not carrying args when dragged to the hotbat

### ISSUE THREAD

**Issue by MastaGooz** [reonZ/mc-ro#2]
Hi ! 

I'm having an issue when I drag a macro inline link to the hotbar : the arguments are not carried and I get :
"caught (in promise) ReferenceError: undefined. args is not defined"

Everything works fine as long as the macro is not dragged into the hotbar.

**Comment by reonZ** [comment]
This module has not been updated for v11 (last update was 14 months ago) where macros were changed to accept arbitrary arguments.

**Comment by MastaGooz** [comment]
I see.

So I did some change to the module so when you drag a macro it creates a new one, changing the macro args directly into their values. If such macro already exists, then it does not create a new one. It does the job !

**Comment by reonZ** [comment]
good to hear :)
